workspace:
  base: /test
  path: toolkit

matrix:
  PHP_VERSION:
    - 8.3
  COMPOSER_BOUNDARY:
    - lowest
    - highest

pipeline:
  composer-install:
    group: composer
    image: fpfis/httpd-php:${PHP_VERSION=8.1}-ci
    secrets: [ github_api_token, gitlab_api_token, composer_auth ]
    environment: &env
      - DOCUMENT_ROOT=/test/toolkit
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    commands:
      - composer install --ansi --no-progress
      - composer outdated --no-dev --locked --direct --minor-only
    when:
      matrix:
        COMPOSER_BOUNDARY: highest

  composer-update-lowest:
    group: composer
    image: fpfis/httpd-php:${PHP_VERSION=8.1}-ci
    secrets: [ github_api_token, gitlab_api_token, composer_auth ]
    environment: *env
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    commands:
      - composer update --prefer-lowest --prefer-stable --ansi --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest
